import * as fs from "fs";
import * as path from "path";
import * as readline from "readline";
import { ENV_SCHEMA } from "../env-schema.js";
import type { EnvVariable } from "../env-schema.js";

function prompt(rl: readline.Interface, question: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(question, (answer) => resolve(answer));
  });
}

function validateValue(variable: EnvVariable, value: string): string | null {
  if (!value && variable.required) {
    if (!variable.defaultValue) {
      return `'${variable.key}' is required and has no default value.`;
    }
  }
  if (value && variable.validate && !variable.validate(value)) {
    return `'${variable.key}' has an invalid value.`;
  }
  return null;
}

async function readExistingEnv(
  filePath: string,
): Promise<Record<string, string>> {
  const result: Record<string, string> = {};
  if (!fs.existsSync(filePath)) return result;

  const content = fs.readFileSync(filePath, "utf-8");
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIndex = trimmed.indexOf("=");
    if (eqIndex === -1) continue;
    const key = trimmed.slice(0, eqIndex).trim();
    const value = trimmed
      .slice(eqIndex + 1)
      .trim()
      .replace(/^["']|["']$/g, "");
    result[key] = value;
  }
  return result;
}

async function writeEnvFile(
  filePath: string,
  values: Record<string, string>,
): Promise<void> {
  const lines: string[] = [
    "# Generated by my-app-tools setup-env script",
    `# Generated at: ${new Date().toISOString()}`,
    "",
  ];

  for (const variable of ENV_SCHEMA.variables) {
    lines.push(`# ${variable.description}`);
    if (!variable.required) {
      lines.push(`# Default: ${variable.defaultValue ?? "none"}`);
    }
    const value = values[variable.key] ?? variable.defaultValue ?? "";
    lines.push(`${variable.key}=${value}`);
    lines.push("");
  }

  fs.writeFileSync(filePath, lines.join("\n"), "utf-8");
}

export async function setupEnv(envFilePath?: string): Promise<void> {
  const targetPath = envFilePath ?? path.resolve(process.cwd(), ".env");
  const existingValues = await readExistingEnv(targetPath);

  console.log("\n🔧 my-app Environment Setup\n");
  console.log(`Target file: ${targetPath}\n`);

  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  const newValues: Record<string, string> = {};

  for (const variable of ENV_SCHEMA.variables) {
    const existing = existingValues[variable.key];
    const displayExisting = existing
      ? variable.sensitive
        ? "***"
        : existing
      : undefined;

    let question = `${variable.key}: ${variable.description}`;
    if (displayExisting !== undefined) {
      question += ` [current: ${displayExisting}]`;
    } else if (variable.defaultValue !== undefined) {
      question += ` [default: ${variable.sensitive ? "***" : variable.defaultValue}]`;
    }
    if (!variable.required) {
      question += " (optional)";
    }
    question += "\n> ";

    let value: string;
    let error: string | null;

    do {
      const input = await prompt(rl, question);
      value =
        input.trim() !== ""
          ? input.trim()
          : (existing ?? variable.defaultValue ?? "");
      error = validateValue(variable, value);
      if (error) {
        console.error(`  ❌ ${error}`);
      }
    } while (error !== null);

    newValues[variable.key] = value;
    console.log(`  ✅ ${variable.key} set\n`);
  }

  rl.close();

  await writeEnvFile(targetPath, newValues);
  console.log(`\n✅ Environment file written to: ${targetPath}`);
  console.log("⚠️  Never commit .env files to version control!\n");
}
